Repository opensearch-project/oui, pull requests merged in 2023-09, with the labels that each got.

#1011 Bump version to `1.3.0-rc.1`
  package.json
Labels: skip-changelog, seasoned-contributor

#987 Replace Avatar in favor of Icon in OuiFacetButtons example
  CHANGELOG.md
  src-docs/src/views/facet/facet.js
Labels: backport 1.x, first-time-contributor

#1014 Add icons for OSD 2.10 release
  CHANGELOG.md
  src-docs/src/views/icon/icons.js
  src/components/icon/__snapshots__/icon.test.tsx.snap
  src/components/icon/assets/chatLeft.js
  src/components/icon/assets/chatLeft.svg
  src/components/icon/assets/chatRight.js
  src/components/icon/assets/chatRight.svg
  src/components/icon/assets/checkInCircleEmpty.js
  src/components/icon/assets/checkInCircleEmpty.svg
  src/components/icon/assets/integrationGeneral.js
  src/components/icon/assets/integrationGeneral.svg
  src/components/icon/assets/integrationObservability.js
  src/components/icon/assets/integrationObservability.svg
  src/components/icon/assets/integrationSearch.js
  src/components/icon/assets/integrationSearch.svg
  src/components/icon/assets/integrationSecurity.js
  src/components/icon/assets/integrationSecurity.svg
  src/components/icon/assets/redeploy.js
  src/components/icon/assets/redeploy.svg
  src/components/icon/assets/thumbsDown.js
  src/components/icon/assets/thumbsDown.svg
  src/components/icon/assets/thumbsUp.js
  src/components/icon/assets/thumbsUp.svg
  src/components/icon/assets/undeploy.js
  src/components/icon/assets/undeploy.svg
  src/components/icon/icon.tsx
Labels: backport 1.x, seasoned-contributor, 1.3

#1016 Override OuiCollapsibleNav background color in `next` theme
  CHANGELOG.md
  src/components/collapsible_nav/_collapsible_nav.scss
  src/global_styling/variables/_collapsible_nav.scss
  src/themes/oui-next/global_styling/variables/_collapsible_nav.scss
Labels: backport 1.x, seasoned-contributor, 1.3

#1019 Add support for null types when deriving JSON from Sass variables
  CHANGELOG.md
  scripts/derive-sass-variable-types.js
Labels: backport 1.x, 1.3, distinguished-contributor

#1021 Bump version to `1.3.0`
  package.json
Labels: skip-changelog, seasoned-contributor

#1030 Fix next light color guidelines
  CHANGELOG.md
  src-docs/src/views/guidelines/_get_sass_vars.js
Labels: backport 1.x, distinguished-contributor, backport 1.3

#1017 Add Dashboards integration workflow
  .github/workflows/build_and_test.yml
  CHANGELOG.md
Labels: backport 1.x, distinguished-contributor

#1026 Update changelog for 1.3 release
  CHANGELOG.md
Labels: distinguished-contributor

#1027 Fix alignment of left icon for OuiListGroupItem
  CHANGELOG.md
  src-docs/src/views/list_group/list_group_extra.js
  src/components/list_group/_list_group_item.scss
Labels: backport 1.x, first-time-contributor

#1024 Add exit code to compile-scss script on failure
  CHANGELOG.md
  scripts/compile-scss.js
Labels: backport 1.x, distinguished-contributor

#1028 Update docsite version selector to use OUI
  CHANGELOG.md
  src-docs/src/assets/version-selector.js
  src-docs/src/components/guide_page/guide_page_header.tsx
  src-docs/src/components/guide_version_selector/guide_version_selector.tsx
  src-docs/src/components/guide_version_selector/index.ts
Labels: backport 1.x, distinguished-contributor

#1037 [1.x] Update changelog for 1.3
  CHANGELOG.md
Labels: distinguished-contributor

#1036 [1.3] Update changelog for 1.3
  CHANGELOG.md
Labels: distinguished-contributor

#1039 Update changelog with 1.1.2 and 1.2.0
  CHANGELOG.md
Labels: distinguished-contributor

#1044 Add crossInCircleEmpty and power icons
  CHANGELOG.md
  src-docs/src/views/icon/icons.js
  src/components/icon/__snapshots__/icon.test.tsx.snap
  src/components/icon/assets/crossInCircleEmpty.js
  src/components/icon/assets/crossInCircleEmpty.svg
  src/components/icon/assets/power.js
  src/components/icon/assets/power.svg
  src/components/icon/icon.tsx
Labels: backport 1.x, distinguished-contributor

#1042 [1.x] Update changelog with 1.1 and 1.2
  CHANGELOG.md
Labels: distinguished-contributor

#1046 Update caniuse db
  CHANGELOG.md
  package.json
  yarn.lock
Labels: backport 1.x, distinguished-contributor

#570 Update README.md
  README.md
Labels: CCI, backport 1.x, skip-changelog

#879 Bump typescript to 4.6.4
  CHANGELOG.md
  i18ntokens.json
  package.json
  src-docs/src/components/guide_section/guide_section.tsx
  src/components/datagrid/data_grid_inmemory_renderer.tsx
  src/components/header/header_links/header_links.tsx
  src/components/icon/icon.test.tsx
  src/components/list_group/pinnable_list_group/pinnable_list_group.tsx
  src/components/markdown_editor/markdown_editor.tsx
  src/components/search_bar/query/default_syntax.ts
  src/components/search_bar/search_bar.tsx
  src/components/selectable/selectable_templates/selectable_template_sitewide.tsx
  src/components/suggest/suggest_item.tsx
  yarn.lock
Labels: backport 1.x, first-time-contributor
