Repository opensearch-project/oui, pull requests merged in 2023-02, with the labels that each got.

#219 [OUI Button]Changed the references of elastic.co to opensearch.org and changed To…
  src-docs/src/views/button/button_as_link.js
  src-docs/src/views/button/button_ghost.js
  src-docs/src/views/button/button_toggle.js
Labels: backport 1.0, OUIDocs

#221 Removed Outdated References of elastic and updated with Opensearch.org
  src-docs/src/views/tabs/tabs.js
Labels: backport 1.0, OUIDocs

#223 Removed outdated reference and updated text in OUI doc steps
  src-docs/src/views/steps/status.js
  src-docs/src/views/steps/steps_complex.js
Labels: backport 1.0, OUIDocs

#224 Removed smokeMoster from Optional styling
  src-docs/src/views/tree_view/compressed.js
Labels: backport 1.0, OUIDocs

#235 Updated text in Section Positions
  src-docs/src/views/bottom_bar/bottom_bar_position.js
Labels: backport 1.0, OUIDocs

#237 Removing message text in the examples section
  src-docs/src/views/modal/confirm_modal_loading.js
Labels: backport 1.0, OUIDocs

#258 Updated the Reziable container
  src-docs/src/views/resizable_container/resizable_container_basic.js
  src-docs/src/views/resizable_container/resizable_panel_collapsible.js
  src-docs/src/views/resizable_container/resizable_panel_collapsible_options.js
  src-docs/src/views/resizable_container/resizable_panel_collapsible_responsive.js
Labels: backport 1.0, OUIDocs

#308 [OUI Docs] Removed the link in the section ColorPalattes
  src-docs/src/views/color_palette/color_palette_example.js
Labels: backport 1.0, OUIDocs

#307 [OUI Docs] updated the title section
  src-docs/src/views/title/title_example.js
Labels: backport 1.0, OUIDocs

#290 [OUI Docs] Updated the links in the section Form Layout
  src-docs/src/views/form_layouts/described_form_group.js
  src-docs/src/views/form_layouts/form_rows.js
Labels: backport 1.0, OUIDocs

#270 Updated link Validation section
  src-docs/src/views/link/link.js
  src-docs/src/views/link/link_validation.js
Labels: backport 1.0, OUIDocs

#260 Updated Side nav
  src-docs/src/views/side_nav/side_nav_complex.js
  src-docs/src/views/side_nav/side_nav_force_open.js
Labels: backport 1.0, OUIDocs

#293 [OUI Docs] Updated the content for the Empty prompt
  src-docs/src/views/empty_prompt/custom.js
  src-docs/src/views/empty_prompt/empty_prompt.js
  src-docs/src/views/empty_prompt/empty_prompt_example.js
  src-docs/src/views/empty_prompt/empty_prompt_loading.js
  src-docs/src/views/empty_prompt/empty_prompt_states.js
  src-docs/src/views/empty_prompt/playground.js
  src-docs/src/views/empty_prompt/simple.js
Labels: backport 1.0, OUIDocs

#291 [OUI Docs] Updated the content for the ToolTip
  src-docs/src/views/tool_tip/icon_tip.js
  src-docs/src/views/tool_tip/tool_tip.js
  src-docs/src/views/tool_tip/tool_tip_example.js
Labels: backport 1.0, OUIDocs

#131 Update breadcrumbs to new styling
  src/components/breadcrumbs/__snapshots__/breadcrumbs.test.tsx.snap
  src/components/breadcrumbs/_breadcrumbs.scss
  src/components/breadcrumbs/_variables.scss
  src/components/breadcrumbs/breadcrumbs.tsx
  src/components/control_bar/__snapshots__/control_bar.test.tsx.snap
  src/components/header/__snapshots__/header.test.tsx.snap
  src/components/header/header_breadcrumbs/__snapshots__/header_breadcrumbs.test.tsx.snap
  src/themes/oui/oui_colors_dark.scss
Labels: backport 1.0

#373 Clean table doc ref
  src-docs/src/views/tables/actions/actions.js
  src-docs/src/views/tables/footer/footer.js
  src-docs/src/views/tables/in_memory/in_memory.js
  src-docs/src/views/tables/in_memory/in_memory_controlled_pagination.js
  src-docs/src/views/tables/in_memory/in_memory_search.js
  src-docs/src/views/tables/in_memory/in_memory_search_callback.js
  src-docs/src/views/tables/in_memory/in_memory_search_external.js
  src-docs/src/views/tables/in_memory/in_memory_selection.js
  src-docs/src/views/tables/mobile/mobile.js
  src-docs/src/views/tables/paginated/paginated.js
  src-docs/src/views/tables/selection/selection.js
  src-docs/src/views/tables/sorting/sorting.js
Labels: backport 1.0, OUIDocs

#380 Add OpenSearch logo
  src/components/icon/assets/logo_opensearch.js
  src/components/icon/assets/logo_opensearch.svg
Labels: backport 1.0

#374 Delete ES reference in tour page
  src-docs/src/components/guide_page/guide_page.js
  src-docs/src/views/tour/managed.js
  src-docs/src/views/tour/managed_hook.js
  src-docs/src/views/tour/tour.js
  yarn.lock
Labels: OUIDocs

#501 [OUI Docs] Updated the Podcast in the section Aspect Ratio
  src-docs/src/views/aspect_ratio/aspect_ratio.js
Labels: backport 1.0, OUIDocs

#372 [OUI Docs] Updated the youtube embed in the section Aspect ratio
  src-docs/src/views/aspect_ratio/aspect_ratio.js
  src-docs/src/views/aspect_ratio/playground.js
Labels: OUIDocs

#368 [OUI Docs] Updated the content and Icons in the section CssUtilityClasses
  src-docs/src/views/utility_classes/utility_classes_overflow.js
  src-docs/src/views/utility_classes/utility_classes_text.js
  src-docs/src/views/utility_classes/utility_classes_vert_align.js
Labels: OUIDocs

#251 Update avatar docs
  src-docs/src/views/avatar/avatar_initials.js
  src-docs/src/views/avatar/avatar_type.js
Labels: backport 1.0, OUIDocs

#382 [Docs] Update README to baseline to project standards
  ADMINS.md
  DEVELOPER_GUIDE.md
  README.md
  RESPONSIBILITIES.md
  SECURITY.md
Labels: backport 1.0, OUIDocs

#371 [OUI Docs] Removed GitHub column from all the tables
  src-docs/src/views/tables/in_memory/in_memory.js
  src-docs/src/views/tables/in_memory/in_memory_controlled_pagination.js
  src-docs/src/views/tables/in_memory/in_memory_search.js
  src-docs/src/views/tables/in_memory/in_memory_search_callback.js
  src-docs/src/views/tables/in_memory/in_memory_search_external.js
  src-docs/src/views/tables/in_memory/in_memory_selection.js
Labels: OUIDocs

#496 Change OUI Icon page
  src-docs/src/views/icon/apps.js
  src-docs/src/views/icon/icon_example.js
  src-docs/src/views/icon/logos.js
  src/components/icon/__snapshots__/icon.test.tsx.snap
  src/components/icon/assets/logo_opensearch.js
  src/components/icon/icon.tsx
Labels: backport 1.0, OUIDocs

#503 Remove writing guidelines
  src-docs/src/routes.js
  src-docs/src/views/guidelines/writing.js
Labels: backport 1.0, OUIDocs

#499 [Docs] Change text to lorem ipsum
  src-docs/src/views/comment/comment.tsx
  src-docs/src/views/comment/comment_list.tsx
  src-docs/src/views/comment/playground.js
  src-docs/src/views/description_list/description_list.js
  src-docs/src/views/description_list/description_list_classes.js
  src-docs/src/views/description_list/description_list_column.js
  src-docs/src/views/description_list/description_list_example.js
  src-docs/src/views/description_list/description_list_inline.js
  src-docs/src/views/description_list/description_list_reverse.js
  src-docs/src/views/description_list/description_list_styling.js
  src-docs/src/views/flyout/flyout_complicated.js
  src-docs/src/views/text/playground.js
  src-docs/src/views/text/text.js
  src-docs/src/views/text/text_small.js
  src-docs/src/views/text/text_width.js
  src-docs/src/views/text_scaling/text_scaling.js
Labels: backport 1.0, OUIDocs

#383 [OUI docs] Keypad: change beta to experimental
  src-docs/src/views/key_pad_menu/key_pad_beta.js
  src-docs/src/views/key_pad_menu/key_pad_menu_example.js
Labels: OUIDocs

#370 [OUI Docs] Removed the chart section that's using elastic charts
  src-docs/src/views/markdown_editor/markdown_plugin_example.js
Labels: OUIDocs

#366 [OUI Docs] Updated the text in the section ErrorBoundary
  src-docs/src/views/error_boundary/error_boundary.js
Labels: OUIDocs

#343 [OUI Docs] Deprecated kibana references
  src-docs/src/views/expression/columns.js
  src-docs/src/views/expression/stringing.tsx
  src-docs/src/views/expression/truncate.js
Labels: OUIDocs

#350 [OUI Docs] Updated the content in the section Messages and loading
  src-docs/src/views/selectable/selectable_example.js
  src-docs/src/views/selectable/selectable_messages.tsx
Labels: OUIDocs

#365 [OUI Docs] Updated the links in the section Markdown Format
  src-docs/src/views/markdown_editor/markdown_format_sink.js
Labels: OUIDocs

#347 [OUI Docs] Updated the content in the section suggest
  src-docs/src/views/suggest/saved_queries.js
  src-docs/src/views/suggest/suggest_example.js
Labels: OUIDocs

#289 [OUI Docs] Updated the content in the section Toast
  src-docs/src/views/toast/danger.js
  src-docs/src/views/toast/guidelines.js
Labels: backport 1.0, OUIDocs

#288 [OUI DOCS] Updated the content in the section Datagrid and schema
  src-docs/src/views/datagrid/datagrid_example.js
  src-docs/src/views/datagrid/schema.js
Labels: backport 1.0, OUIDocs

#500 Clean Homepage
  src-docs/src/views/home/home_view.js
Labels: backport 1.0, OUIDocs

#250 Update Control Bar Docs
  src-docs/src/views/control_bar/control_bar.js
  src-docs/src/views/control_bar/tabs.js
Labels: backport 1.0, OUIDocs

#253 Update callout docs
  src-docs/src/views/call_out/danger.js
  src-docs/src/views/call_out/info.js
  src-docs/src/views/call_out/success.js
  src-docs/src/views/call_out/warning.js
Labels: backport 1.0, OUIDocs

#330 Updated the section Collapsable Nav
  src-docs/src/views/collapsible_nav/collapsible_nav.tsx
  src-docs/src/views/collapsible_nav/collapsible_nav_all.tsx
  src-docs/src/views/collapsible_nav/collapsible_nav_example.js
  src-docs/src/views/collapsible_nav/collapsible_nav_group.tsx
  src-docs/src/views/collapsible_nav/collapsible_nav_list.tsx
Labels: OUIDocs

#315 [OUI Docs] Updated the logo to logoOpenSearch
  src-docs/src/views/page/page_template.js
Labels: OUIDocs

#252 Update Comment List Docs
  src-docs/src/views/comment/comment.tsx
  src-docs/src/views/comment/comment_example.js
  src-docs/src/views/comment/comment_list.tsx
Labels: backport 1.0, OUIDocs

#367 [OUI Docs] Updated the section Beacon
  src-docs/src/views/beacon/beacon_example.js
Labels: OUIDocs

#502 [Docs] Update getting_started.md to remove elastic reference and other changes
  src-docs/src/views/guidelines/getting_started.md
Labels: backport 1.0, OUIDocs

#536 Update backport workflow
  .github/workflows/backport.yml
Labels: backport 1.0

#257 fix: overlay mask onClick been called multiple times
  src/components/overlay_mask/overlay_mask.tsx
Labels: backport 1.0

#202 Update whitesource includes and excludes to make sense
  whitesource.config
Labels: enhancement, backport 1.0

#546 Add permissions to the workflow
  .github/workflows/release-drafter.yml
Labels: backport 1.0
