Repository opensearch-project/oui, pull requests merged in 2023-04, with the labels that each got.

#636 Add build artifacts to release
  .github/workflows/release-drafter.yml
Labels: backport 1.0, backport 1.x

#662 Publish OUI to npmjs using tarball
  jenkins/release.JenkinsFile
Labels: backport 1.0, backport 1.x

#668 Update CODEOWNERS
  .github/CODEOWNERS
Labels: backport 1.x

#658 Add icons for Dashboards 2.7
  src-docs/src/views/icon/icons.js
  src/components/icon/__snapshots__/icon.test.tsx.snap
  src/components/icon/assets/polygon.js
  src/components/icon/assets/polygon.svg
  src/components/icon/assets/radius.js
  src/components/icon/assets/radius.svg
  src/components/icon/assets/vis_builder.js
  src/components/icon/assets/vis_builder.svg
  src/components/icon/assets/vis_builder_saved_object.js
  src/components/icon/assets/vis_builder_saved_object.svg
  src/components/icon/assets/vis_query_dql.js
  src/components/icon/assets/vis_query_dql.svg
  src/components/icon/assets/vis_query_ppl.js
  src/components/icon/assets/vis_query_ppl.svg
  src/components/icon/assets/vis_query_promql.js
  src/components/icon/assets/vis_query_promql.svg
  src/components/icon/assets/vis_query_sql.js
  src/components/icon/assets/vis_query_sql.svg
  src/components/icon/icon.tsx
Labels: backport 1.x, backport 1.1

#687 Add leading slash to test in .npmignore
  .npmignore
Labels: backport 1.0, backport 1.x, backport 1.1

#650 [CCI] Update tabbable dependency
  i18ntokens.json
  package.json
  src/components/context_menu/context_menu_panel.tsx
  src/components/datagrid/data_grid.tsx
  src/components/datagrid/data_grid_body.tsx
  src/components/datagrid/data_grid_cell.tsx
  src/components/datagrid/data_grid_control_header_cell.tsx
  src/components/datagrid/data_grid_header_cell.tsx
  src/components/popover/input_popover.tsx
  src/components/popover/popover.tsx
  yarn.lock
Labels: CCI

#652 [CCI] Update react-window and react-virtualized-auto-sizer dependencies
  package.json
  src/components/datagrid/data_grid.test.tsx
  yarn.lock
Labels: CCI

#651 [CCI] Update dropzone dependency
  package.json
  src/components/markdown_editor/__snapshots__/markdown_editor.test.tsx.snap
  yarn.lock
Labels: CCI

#655 [CCI] Migrate from faker to @faker-js/faker
  package.json
  src-docs/src/views/datagrid/additional_controls.js
  src-docs/src/views/datagrid/column_actions.js
  src-docs/src/views/datagrid/column_cell_actions.js
  src-docs/src/views/datagrid/column_widths.js
  src-docs/src/views/datagrid/container.js
  src-docs/src/views/datagrid/control_columns.js
  src-docs/src/views/datagrid/datagrid.js
  src-docs/src/views/datagrid/focus.js
  src-docs/src/views/datagrid/footer_row.js
  src-docs/src/views/datagrid/in_memory.js
  src-docs/src/views/datagrid/in_memory_enhancements.js
  src-docs/src/views/datagrid/in_memory_pagination.js
  src-docs/src/views/datagrid/in_memory_sorting.js
  src-docs/src/views/datagrid/row_height_options.js
  src-docs/src/views/datagrid/schema.js
  src-docs/src/views/datagrid/styling.js
  src-docs/src/views/datagrid/virtualization.js
  src-docs/src/views/datagrid/virtualization_constrained.js
  src-docs/src/views/image/float.js
  src-docs/src/views/resizable_container/resizable_container_basic.js
  src-docs/src/views/resizable_container/resizable_container_reset_values.js
  src-docs/src/views/resizable_container/resizable_container_vertical.js
  src-docs/src/views/resizable_container/resizable_panel_collapsible.js
  src-docs/src/views/resizable_container/resizable_panel_collapsible_options.js
  src-docs/src/views/resizable_container/resizable_panel_collapsible_responsive.js
  yarn.lock
Labels: CCI

#695 Fix aliasing regression in post install script
  scripts/postinstall.js
Labels: backport 1.0, backport 1.x, backport 1.1

#672 Update loader-utils to 1.4.2
  yarn.lock
Labels: backport 1.0, backport 1.1

#657 [CCI] Remove unused chart theme code
  scripts/compile-oui.js
  scripts/dtsgenerator.js
  src-docs/src/theme_cascadia_dark.scss
  src-docs/src/theme_cascadia_light.scss
  src-docs/src/theme_dark.scss
  src-docs/src/theme_light.scss
Labels: CCI

#713 Bump sass-loader to 10.4.1
  yarn.lock
Labels: backport 1.x, backport 1.1
