Repository opensearch-project/oui, pull requests merged in 2023-12, with the labels that each got.

#1155 [OSCI] Update deprecated Babel plugins
  .babelrc.js
  CHANGELOG.md
  i18ntokens.json
  package.json
  yarn.lock
Labels: backport 1.x, first-time-contributor, OSCI

#1050 Update changelog regex for new changelog structure
  src-docs/src/views/package/changelog.js
Labels: backport 1.x, skip-changelog, distinguished-contributor

#1134 [BUG] Tree view expanded view #1118
  CHANGELOG.md
  src/components/tree_view/tree_view.scss
Labels: first-time-contributor, OSCI

#1170 Skip build and test on dependabot
  .github/workflows/build_and_test.yml
  CHANGELOG.md
Labels: backport 1.x, distinguished-contributor

#1113 [Fix] Rename crossInACircleFilled Asset Files and Ensure Backward Compatibility
  CHANGELOG.md
  src-docs/src/views/icon/icons.js
  src/components/icon/__snapshots__/icon.test.tsx.snap
  src/components/icon/assets/crossInCircleFilled.js
  src/components/icon/assets/crossInCircleFilled.svg
  src/components/icon/icon.tsx
Labels: first-time-contributor, OSCI

#1141 Add docking icons
  CHANGELOG.md
  src-docs/src/views/icon/icons.js
  src/components/icon/__snapshots__/icon.test.tsx.snap
  src/components/icon/assets/dockedBottom.js
  src/components/icon/assets/dockedBottom.svg
  src/components/icon/assets/dockedDetached.js
  src/components/icon/assets/dockedDetached.svg
  src/components/icon/assets/dockedLeft.js
  src/components/icon/assets/dockedLeft.svg
  src/components/icon/assets/dockedRight.js
  src/components/icon/assets/dockedRight.svg
  src/components/icon/assets/dockedTakeover.js
  src/components/icon/assets/dockedTakeover.svg
  src/components/icon/assets/dockedTop.js
  src/components/icon/assets/dockedTop.svg
  src/components/icon/icon.tsx
Labels: backport 1.x, first-time-contributor

#1183 [1.x] Bump 1.4.0
  package.json
Labels: skip-changelog, distinguished-contributor

#1188 Move Sean to Emeritus
  .github/CODEOWNERS
  CHANGELOG.md
  MAINTAINERS.md
Labels: backport 1.x, all-star-contributor

#1190 Sync CHANGELOG prior to 1.4 release
  CHANGELOG.md
Labels: skip-changelog, all-star-contributor
