Repository opensearch-project/oui, pull requests merged in 2023-05, with the labels that each got.

#694 [CCI] Move OuiBottomBar default inline styles to the CSS file
  src/components/bottom_bar/__snapshots__/bottom_bar.test.tsx.snap
  src/components/bottom_bar/_bottom_bar.scss
  src/components/bottom_bar/bottom_bar.tsx
  src/components/page/__snapshots__/page_template.test.tsx.snap
Labels: CCI

#717 [CCI] Bump rimraf from 3.0.2 to 5.0.0
  package.json
  scripts/compile-clean.js
  yarn.lock
Labels: CCI, backport 1.x

#721 [CCI] Remove Elastic References from OuiBasicTable
  src-docs/src/views/tables/actions/actions.js
Labels: CCI, backport 1.x

#726 [Data Grid] Fix logic when pageSize larger than number of rows
  src/components/datagrid/data_grid_body.tsx
Labels: CCI

#730 [CCI] Add github-merit-badger workflow
  .github/workflows/github-workflow-badger.yml
Labels: CCI

#752 Add Ashwin and Josh to the maintainers list
  .github/CODEOWNERS
  MAINTAINERS.md
Labels: all-star-contributor

#759 Deprecate ```iconType``` and ```iconProps``` from ```OuiPageHeader```
  src/components/page/page_header/page_header.tsx
  src/components/page/page_header/page_header_content.tsx
Labels: CCI, backport 1.x, first-time-contributor

#781 Add anomaly detection icon
  src-docs/src/views/icon/icons.js
  src/components/icon/__snapshots__/icon.test.tsx.snap
  src/components/icon/assets/anomaly_detection.js
  src/components/icon/assets/anomaly_detection.svg
  src/components/icon/icon.tsx
Labels: backport 1.x, all-star-contributor, 1.2

#778 Fix breadcrumb styling with a single breadcrumb
  src/components/breadcrumbs/_breadcrumbs.scss
  src/components/breadcrumbs/breadcrumbs.tsx
  src/components/header/__snapshots__/header.test.tsx.snap
Labels: backport 1.x, all-star-contributor, 1.2

#775 Fix combo box onFocus bug
  src/components/combo_box/combo_box.tsx
Labels: backport 1.x, all-star-contributor, 1.2

#787 [1.x] Bump version to 1.2.0-rc.1
  package.json
Labels: 1.2

#789 Add @andreymyssak and @SergeyMyssak as co-maintainers
  .github/CODEOWNERS
  MAINTAINERS.md
Labels: backport 1.x, all-star-contributor

#790 Fix release drafter workflow
  .github/workflows/release-drafter.yml
Labels: backport 1.x, all-star-contributor, 1.2

#795 Bump version to 1.2.0
  package.json
Labels: 1.2

#794 Update affiliation of Andrey and Sergey
  MAINTAINERS.md
Labels: backport 1.x, all-star-contributor
