Repository opensearch-project/oui, pull requests merged in 2023-11, with the labels that each got.

#1053 Added onFullScreenChange to OuiDataGrid
  CHANGELOG.md
  src-docs/src/views/datagrid/datagrid.js
  src/components/datagrid/data_grid.tsx
Labels: backport 1.x, repeat-contributor

#1075 Fix integration test workflows
  .github/workflows/build_and_test.yml
  CHANGELOG.md
Labels: backport 1.x, distinguished-contributor

#1095 Remove `babel-core` dep and upgrade `babel-template`
  CHANGELOG.md
  package.json
  scripts/babel/proptypes-from-ts-props/index.js
  yarn.lock
Labels: backport 1.x, seasoned-contributor

#1051 Add slugs to markdown headers
  CHANGELOG.md
  package.json
  src-docs/src/components/guide_markdown_format/guide_markdown_format.tsx
  src/components/markdown_editor/plugins/markdown_default_plugins.tsx
  yarn.lock
Labels: backport 1.x, distinguished-contributor

#1114 [Fix] Add error handling when staged files are empty
  CHANGELOG.md
  scripts/test-staged.js
Labels: backport 1.x, first-time-contributor, OSCI
