Repository opensearch-project/oui, pull requests merged in 2023-10, with the labels that each got.

#1058 Fix docgen babel plugin
  package.json
  scripts/compile-clean.js
  yarn.lock
Labels: backport 1.x, skip-changelog

#1065 Changes made in Developer Guide
  DEVELOPER_GUIDE.md
Labels: skip-changelog, first-time-contributor, OSCI

#1066 [OSCI] Docs/modal width
  CHANGELOG.md
  src-docs/src/views/modal/modal_example.js
  src-docs/src/views/modal/modal_width.js
Labels: backport 1.x, first-time-contributor, OSCI

#1074 Bump to version 2.0.0
  package.json
Labels: skip-changelog, distinguished-contributor

#1073 Bump version to 1.4.0-alpha.1
  package.json
Labels: skip-changelog, distinguished-contributor

#1064 Add figma link on navbar
  CHANGELOG.md
  src-docs/src/components/guide_page/guide_page_header.tsx
Labels: backport 1.x, first-time-contributor, OSCI

#1069 [OSCI] Bug fix: Correct file path for importing Query component
  CHANGELOG.md
  src/components/search_bar/filters/field_value_selection_filter.tsx
  src/components/search_bar/filters/field_value_toggle_filter.tsx
  src/components/search_bar/filters/field_value_toggle_group_filter.tsx
  src/components/search_bar/filters/is_filter.tsx
  src/components/search_bar/search_bar.tsx
Labels: backport 1.x, first-time-contributor, OSCI

#1083 [Fix] Updated new polygon icon svg
  CHANGELOG.md
  src/components/icon/__snapshots__/icon.test.tsx.snap
  src/components/icon/assets/polygon.js
  src/components/icon/assets/polygon.svg
Labels: first-time-contributor

#1084 [Fix] Remove Emphasized side nav sections from OUI docs site
  CHANGELOG.md
  src-docs/src/views/side_nav/side_nav_emphasis.js
  src-docs/src/views/side_nav/side_nav_example.js
Labels: backport 1.x, first-time-contributor

#890 Remove Internet Explorer specific code
  .browserslistrc
  CHANGELOG.md
  packages/react-datepicker.js
  src-docs/src/components/guide_section/guide_section.tsx
Labels: backport 1.x, first-time-contributor

#1072 Made recommended changes to git pre-commit hook
  CHANGELOG.md
  package.json
Labels: first-time-contributor

#1105 Bump `@types/react` and `csstype`
  CHANGELOG.md
  i18ntokens.json
  package.json
  src/components/tabs/tabbed_content/tabbed_content.tsx
  yarn.lock
Labels: backport 1.x, all-star-contributor

#1106 Bump version to 1.4.0-alpha.2
  package.json
Labels: skip-changelog, distinguished-contributor

#1112 [OSCI] Fix Typo in `wiki/consuming.md`
  wiki/consuming.md
Labels: backport 1.x, skip-changelog, first-time-contributor

#1111 [Fix] "Guidelines" Documentation Render Blank Page
  CHANGELOG.md
  src-docs/src/views/guidelines/colors/_utilities.js
  src-docs/src/views/guidelines/colors/color_section.js
  src-docs/src/views/guidelines/colors/core_palette.js
  src-docs/src/views/guidelines/colors/vis_palette.js
  src-docs/src/views/guidelines/sass.js
Labels: backport 1.x, first-time-contributor
