Repository opensearch-project/oui, pull requests merged in 2023-07, with the labels that each got.

#831 [CCI] Revert changes to chart themes
  scripts/compile-oui.js
  scripts/dtsgenerator.js
  src-docs/src/theme_dark.scss
  src-docs/src/theme_light.scss
  src-docs/src/theme_next_dark.scss
  src-docs/src/theme_next_light.scss
  src-docs/src/views/markdown_editor/markdown_editor_with_plugins.js
  src/themes/charts/theme.scss
  src/themes/charts/themes.ts
Labels: backport 1.x, skip-changelog, seasoned-contributor

#894 Add autocut label to changelog verifier skip
  .github/workflows/changelog_verifier.yml
Labels: backport 1.x, skip-changelog, distinguished-contributor

#871 Fix `autofill` text color in dark themes
  CHANGELOG.md
  src/global_styling/mixins/_form.scss
  src/themes/oui-next/global_styling/mixins/_form.scss
Labels: backport 1.x, all-star-contributor

#907 Remove kibana text references from docs site
  src-docs/src/views/avatar/avatar_example.js
  src-docs/src/views/code_editor/code_editor_example.js
  src-docs/src/views/collapsible_nav/collapsible_nav_example.js
  src-docs/src/views/empty_prompt/empty_prompt_example.js
  src-docs/src/views/form_compressed/complex_example.js
  src-docs/src/views/guidelines/sass.js
  src-docs/src/views/header/header_alert.js
  src-docs/src/views/markdown_editor/markdown_format_sink.js
  src-docs/src/views/progress/progress_fixed.js
  src-docs/src/views/search_bar/search_bar_example.js
  src-docs/src/views/search_bar/search_bar_filters.js
  src-docs/src/views/selectable/search.tsx
  src-docs/src/views/selectable/selectable_example.js
  src-docs/src/views/side_nav/side_nav_example.js
  src-docs/src/views/toast/toast_list.js
Labels: skip-changelog, repeat-contributor

#910 Doc Site - Add dark prop toggles
  CHANGELOG.md
  src-docs/src/views/collapsible_nav/collapsible_nav_list.tsx
  src-docs/src/views/header/header_dark.tsx
Labels: repeat-contributor
