Repository opensearch-project/oui, pull requests merged in 2023-03, with the labels that each got.

#534 Update content in the section Card
  src-docs/src/views/card/card.js
  src-docs/src/views/card/card_beta.js
  src-docs/src/views/card/card_children.js
  src-docs/src/views/card/card_display.js
  src-docs/src/views/card/card_example.js
  src-docs/src/views/card/card_footer.js
  src-docs/src/views/card/card_image.js
  src-docs/src/views/card/card_layout.js
  src-docs/src/views/card/card_selectable.js
Labels: backport 1.0, OUIDocs

#533 Remove Elastic Charts docs
  src-docs/src/routes.js
  src-docs/src/views/elastic_charts/category_chart.js
  src-docs/src/views/elastic_charts/category_example.js
  src-docs/src/views/elastic_charts/data.js
  src-docs/src/views/elastic_charts/pie.js
  src-docs/src/views/elastic_charts/pie_alts.js
  src-docs/src/views/elastic_charts/pie_example.js
  src-docs/src/views/elastic_charts/pie_slices.js
  src-docs/src/views/elastic_charts/shared.js
  src-docs/src/views/elastic_charts/sizes.js
  src-docs/src/views/elastic_charts/sparklines.js
  src-docs/src/views/elastic_charts/sparklines_example.js
  src-docs/src/views/elastic_charts/theming.js
  src-docs/src/views/elastic_charts/theming_categorical.js
  src-docs/src/views/elastic_charts/theming_example.js
  src-docs/src/views/elastic_charts/time_chart.js
  src-docs/src/views/elastic_charts/time_example.js
  src-docs/src/views/elastic_charts/treemap.js
Labels: backport 1.0, OUIDocs

#532 Ignore WhiteSource branches for build and test
  .github/workflows/build_and_test.yml
Labels: backport 1.0

#535 Delete Kibana reference in commands
  wiki/component-development.md
Labels: OUIDocs

#207 Update front-matter from 2.1.2 to 4.0.2
  package.json
  yarn.lock
Labels: dependencies, backport 1.0

#549 Update Notification event page
  src-docs/src/views/notification_event/notification_event.js
  src-docs/src/views/notification_event/notification_event_example.js
  src-docs/src/views/notification_event/notification_event_flexible.js
  src-docs/src/views/notification_event/notification_event_props_methods.js
  src-docs/src/views/notification_event/notifications_feed.js
Labels: backport 1.0, OUIDocs

#558 Remove the illustration from the folders
  src-docs/src/index.html
  src-docs/src/views/home/home_illustration.tsx
Labels: backport 1.0, OUIDocs

#109 oui docs - headers page changes
  src-docs/src/views/header/header.js
  src-docs/src/views/header/header_elastic_pattern.js
  src-docs/src/views/header/header_links.js
  src-docs/src/views/header/header_position.js
  src-docs/src/views/header/header_sections.js
  src-docs/src/views/header/header_stacked.js
Labels: backport 1.0, OUIDocs

#541 [Security] remove update-token-changelog and fix other securities
  package.json
  scripts/update-token-changelog.js
  wiki/releasing-versions.md
  yarn.lock
Labels: backport 1.0

#576 [CCI] Update Elastic links to OpenSearch ones (#557)
  src-docs/src/index.html
  src-docs/src/views/card/card_image.js
  wiki/creating-components-manually.md
  wiki/creating-icons.md
  wiki/documentation-guidelines.md
  wiki/releasing-versions.md
Labels: backport 1.0, CCI

#579 Update header icon and favicon
  src-docs/src/components/guide_page/guide_page_header.tsx
  src-docs/src/images/favicon/dev/favicon-16x16.png
  src-docs/src/images/favicon/dev/favicon-32x32.png
  src-docs/src/images/favicon/dev/favicon-96x96.png
  src-docs/src/images/favicon/prod/favicon-16x16.png
  src-docs/src/images/favicon/prod/favicon-32x32.png
  src-docs/src/images/favicon/prod/favicon-96x96.png
Labels: backport 1.0

#578 [CCI] Fix deprecated webpack configuration
  src-docs/webpack.config.js
  src/webpack.config.js
Labels: backport 1.0, CCI

#566 Readme Opensearch Logo linking to non-existent file [CCI]
  README.md
Labels: CCI

#608 [CCI] Change OuiTitle size property to m in tooltip example
  src-docs/src/views/tool_tip/tool_tip_example.js
Labels: backport 1.0, CCI, backport 1.x

#603 [CCI] Update logo_opensearch.js file
  src/components/icon/__snapshots__/icon.test.tsx.snap
  src/components/icon/assets/logo_opensearch.js
  src/components/icon/assets/logo_opensearch.svg
Labels: CCI, backport 1.x

#599 [CCI] Fix yo-doc and yo-component crashes
  package.json
  yarn.lock
Labels: backport 1.0, CCI, backport 1.x

#597 [CCI] Create OuiLoadingDashboards component
  src-docs/src/views/loading/loading_dashboards.tsx
  src-docs/src/views/loading/loading_example.js
  src-docs/src/views/loading/playground.js
  src/components/index.js
  src/components/loading/__snapshots__/loading_dashboards.test.tsx.snap
  src/components/loading/_index.scss
  src/components/loading/_loading_dashboards.scss
  src/components/loading/index.ts
  src/components/loading/loading_dashboards.test.tsx
  src/components/loading/loading_dashboards.tsx
Labels: CCI, backport 1.x

#621 [CCI] Update header logo defaults
  src/components/header/__snapshots__/header_logo.test.tsx.snap
  src/components/header/header_logo.tsx
Labels: CCI, needs backport

#606 [CCI] Add deprecation comments to OuiLoadingElastic and OuiLoadingKibana
  src/components/loading/__snapshots__/loading_elastic.test.tsx.snap
  src/components/loading/__snapshots__/loading_kibana.test.tsx.snap
  src/components/loading/loading_elastic.test.tsx
  src/components/loading/loading_elastic.tsx
  src/components/loading/loading_kibana.test.tsx
  src/components/loading/loading_kibana.tsx
  src/utils/deprecated/__snapshots__/deprecated.test.tsx.snap
  src/utils/deprecated/deprecated.test.tsx
  src/utils/deprecated/deprecated.tsx
  src/utils/deprecated/index.ts
  src/utils/index.ts
Labels: CCI, needs backport
