Repository opensearch-project/oui, pull requests merged in 2023-06, with the labels that each got.

#751 fixed invalid link in FAQ.md
  FAQ.md
Labels: first-time-contributor

#764 Updated bug issue template
  .github/ISSUE_TEMPLATE/bug_template.md
Labels: first-time-contributor

#768 [CCI] Bump @faker-js/faker to v8
  package.json
  src-docs/src/views/datagrid/additional_controls.js
  src-docs/src/views/datagrid/column_actions.js
  src-docs/src/views/datagrid/column_cell_actions.js
  src-docs/src/views/datagrid/column_widths.js
  src-docs/src/views/datagrid/container.js
  src-docs/src/views/datagrid/control_columns.js
  src-docs/src/views/datagrid/datagrid.js
  src-docs/src/views/datagrid/focus.js
  src-docs/src/views/datagrid/footer_row.js
  src-docs/src/views/datagrid/in_memory.js
  src-docs/src/views/datagrid/in_memory_enhancements.js
  src-docs/src/views/datagrid/in_memory_pagination.js
  src-docs/src/views/datagrid/in_memory_sorting.js
  src-docs/src/views/datagrid/schema.js
  src-docs/src/views/datagrid/styling.js
  src-docs/src/views/datagrid/virtualization.js
  src-docs/src/views/datagrid/virtualization_constrained.js
  yarn.lock
Labels: CCI, valued-contributor

#798 [CCI] Update the default branch
  FAQ.md
  scripts/deploy/deploy_docs
  scripts/update-changelog-version.js
  src-docs/src/views/datagrid/datagrid_example.js
  src-docs/src/views/guidelines/sass.js
  src-docs/src/views/home/home_view.js
  src-docs/src/views/package/changelog.js
  src-docs/src/views/package/i18n_tokens.js
  src-docs/src/views/tool_tip/tool_tip_example.js
  wiki/documentation-guidelines.md
Labels: valued-contributor

#814 Make font consumption happen using CSS variables
  src/components/suggest/_suggest_item.scss
  src/global_styling/css_variables/_fonts.scss
  src/global_styling/css_variables/_index.scss
  src/global_styling/index.scss
  src/global_styling/mixins/_typography.scss
  src/global_styling/reset/_reset.scss
  src/global_styling/variables/_typography.scss
Labels: seasoned-contributor

#813 Enable local consumption of OUI
  .npmignore
  .sass-lint.yml
  package.json
  scripts/preinstall.js
Labels: seasoned-contributor

#763 Remove ```iconType``` and ```iconProps``` from ```OuiPageHeader```
  src-docs/src/views/page/page_bottom_bar.js
  src-docs/src/views/page/page_centered_content.js
  src-docs/src/views/page/page_custom_content.js
  src-docs/src/views/page/page_new.js
  src-docs/src/views/page/page_restricting_width.js
  src-docs/src/views/page/page_simple_empty_content.js
  src-docs/src/views/page_header/page_header.js
  src-docs/src/views/page_header/page_header_example.js
  src-docs/src/views/page_header/playground.js
  src/components/page/page_header/__snapshots__/page_header.test.tsx.snap
  src/components/page/page_header/__snapshots__/page_header_content.test.tsx.snap
  src/components/page/page_header/_page_header_content.scss
  src/components/page/page_header/page_header.test.tsx
  src/components/page/page_header/page_header.tsx
  src/components/page/page_header/page_header_content.test.tsx
  src/components/page/page_header/page_header_content.tsx
Labels: first-time-contributor

#812 [CCI] Remove Split buttons from OUI docs
  src-docs/src/views/button/button_example.js
  src-docs/src/views/button/split_button.js
Labels: CCI, valued-contributor

#643 Change PR template to say fixes issues
  .github/pull_request_template.md
Labels: backport 1.0, backport 1.x

#660 Add props and examples for the combobox
  src-docs/src/views/combo_box/combo_box_custom_icon.js
  src-docs/src/views/combo_box/combo_box_default_icon.js
  src-docs/src/views/combo_box/combo_box_example.js
Labels: backport 1.x

#806 [OuiComboBox] Add docs for icon and revise example for clearOnBlur
  src-docs/src/views/combo_box/clear_on_blur.js
  src-docs/src/views/combo_box/combo_box_example.js
  src-docs/src/views/combo_box/combo_box_icon.js
Labels: backport 1.x, seasoned-contributor

#815 Bump version to 1.3.0-alpha.1
  package.json
Labels: 1.3

#819 [New Theme] Introduce the first installment of the new look and feel
  src/components/text/_text.scss
  src/theme_dark.scss
  src/theme_light.scss
  src/themes/oui-cascadia/global_styling/mixins/_button.scss
  src/themes/oui-cascadia/global_styling/mixins/_typography.scss
  src/themes/oui-cascadia/global_styling/variables/_colors.scss
  src/themes/oui-cascadia/global_styling/variables/_typography.scss
  src/themes/oui-cascadia/oui_cascadia_colors_dark.scss
Labels: seasoned-contributor

#716 [CCI] Update dependencies
  package.json
  yarn.lock
Labels: CCI

#801 Disable emoticon in markdown renderer by default
  src/components/markdown_editor/plugins/markdown_default_plugins.tsx
Labels: first-time-contributor

#854 [1.1] Chore/bump version 1.1.2
  package.json
Labels: repeat-contributor

#640 Fix accessibility in doc site
  src-docs/src/assets/version-selector.js
  src-docs/src/views/suggest/global_filter_item.js
  src-docs/src/views/tool_tip/tool_tip.js
Labels: backport 1.x

#718 Update changelog with 1.1 info
  CHANGELOG.md
Labels: backport 1.x, backport 1.1

#842 Remove all doc site usages of 'panelled' prop in OuiPageBody components
  src-docs/src/views/app_view.js
  src-docs/src/views/page/page_bottom_bar.js
  src-docs/src/views/page/page_centered_content.js
  src-docs/src/views/page/page_restricting_width.js
Labels: backport 1.x, repeat-contributor

#852 Change deps to keep in preinstall script
  scripts/preinstall.js
Labels: backport 1.x, distinguished-contributor

#720 [CCI] Normalize interlink URL usage
  src-docs/src/views/badge/badge_example.js
  src-docs/src/views/call_out/danger.js
  src-docs/src/views/call_out/warning.js
  src-docs/src/views/card/card_footer.js
  src-docs/src/views/card/card_image.js
  src-docs/src/views/card/card_layout.js
  src-docs/src/views/datagrid/additional_controls.js
  src-docs/src/views/datagrid/container.js
  src-docs/src/views/datagrid/datagrid.js
  src-docs/src/views/datagrid/in_memory.js
  src-docs/src/views/datagrid/in_memory_enhancements.js
  src-docs/src/views/datagrid/in_memory_pagination.js
  src-docs/src/views/datagrid/in_memory_sorting.js
  src-docs/src/views/datagrid/virtualization.js
  src-docs/src/views/datagrid/virtualization_constrained.js
  src-docs/src/views/flyout/flyout_banner.js
  src-docs/src/views/header/header.js
  src-docs/src/views/header/header_alert.js
  src-docs/src/views/header/header_elastic_pattern.js
  src-docs/src/views/header/header_example.js
  src-docs/src/views/header/header_sections.js
  src-docs/src/views/key_pad_menu/key_pad_beta.js
  src-docs/src/views/key_pad_menu/key_pad_menu.js
  src-docs/src/views/key_pad_menu/key_pad_menu_example.js
  src-docs/src/views/link/link.js
  src-docs/src/views/link/link_example.js
  src-docs/src/views/list_group/list_group_item_color.tsx
  src-docs/src/views/progress/progress_fixed.js
  src-docs/src/views/suggest/hashtag_popover.js
  src-docs/src/views/tables/auto/auto.js
  src-docs/src/views/tables/basic/basic.js
  src-docs/src/views/tables/custom/custom.js
  src-docs/src/views/text/playground.js
  src-docs/src/views/text/text.js
  src-docs/src/views/text/text_color.js
  src-docs/src/views/toast/success.js
  src-docs/src/views/toast/toast_list.js
Labels: CCI, backport 1.x

#863 [New Theme] Rename aliased CSS assets
  CHANGELOG.md
  scripts/compile-scss.js
  scripts/postinstall.js
Labels: backport 1.x, all-star-contributor

#865 Bump version to 1.3.0-alpha.2
  package.json
Labels: skip-changelog, distinguished-contributor

#862 Upgrade the backport workflow
  .github/workflows/backport.yml
  CHANGELOG.md
Labels: backport 1.x, distinguished-contributor
