Repository opensearch-project/oui, pull requests merged in 2023-08, with the labels that each got.

#959 Fix blurry breadcrumb text
  CHANGELOG.md
  src/components/breadcrumbs/_breadcrumbs.scss
  src/components/breadcrumbs/_variables.scss
  src/themes/oui-next/oui_next_colors_dark.scss
  src/themes/oui/oui_colors_dark.scss
Labels: backport 1.x, distinguished-contributor

#665 Add build steps to workflow
  .github/workflows/build_and_test.yml
  CHANGELOG.md
Labels: backport 1.x

#961 Set link to use semi bold font weight
  CHANGELOG.md
  src/components/link/_mixins.scss
Labels: backport 1.x, distinguished-contributor

#912 Bump `node-sass` to a version based on `libsas@3.6.5`
  CHANGELOG.md
  package.json
  yarn.lock
Labels: backport 1.x, all-star-contributor

#900 Bump node version to 18.16.0
  .nvmrc
  CHANGELOG.md
  package.json
  yarn.lock
Labels: backport 1.x, distinguished-contributor

#969 Revert #912
  CHANGELOG.md
  package.json
  yarn.lock
Labels: backport 1.x, skip-changelog, distinguished-contributor

#962 Clean up focus background implementation
  CHANGELOG.md
  src/global_styling/mixins/_states.scss
  src/global_styling/variables/_states.scss
  src/themes/oui-next/global_styling/mixins/_states.scss
  src/themes/oui-next/global_styling/variables/_states.scss
Labels: backport 1.x, distinguished-contributor

#936 Theme (Header) - update next background
  CHANGELOG.md
  src/themes/oui-next/global_styling/variables/_header.scss
Labels: valued-contributor

#968 Feat (CollapsibleNavGroup): Make background colors theme-able
  CHANGELOG.md
  src/components/collapsible_nav/_index.scss
  src/components/collapsible_nav/collapsible_nav_group/_collapsible_nav_group.scss
  src/components/collapsible_nav/collapsible_nav_group/collapsible_nav_group.tsx
  src/global_styling/variables/_collapsible_nav.scss
  src/global_styling/variables/_index.scss
  src/themes/oui-next/global_styling/variables/_collapsible_nav.scss
  src/themes/oui-next/global_styling/variables/_index.scss
Labels: backport 1.x, valued-contributor

#974 Schema-item
  CHANGELOG.md
  src-docs/src/routes.js
  src-docs/src/views/schema/schema.tsx
  src-docs/src/views/schema/schema_example.js
  src-docs/src/views/schema/schema_group.tsx
  src/components/index.js
  src/components/index.scss
  src/components/schema/__snapshots__/schema_item.test.tsx.snap
  src/components/schema/_index.scss
  src/components/schema/_schema_item.scss
  src/components/schema/index.ts
  src/components/schema/schema_item.test.tsx
  src/components/schema/schema_item.tsx
Labels: first-time-contributor

#981 Update next light theme primary color to #07827E
  CHANGELOG.md
  src/themes/oui-next/global_styling/variables/_colors.scss
Labels: backport 1.x, distinguished-contributor

#977 Bump `node-sass` to a version based on `libsass@3.6.5`
  CHANGELOG.md
  package.json
  src-docs/src/components/guide_components.scss
  src/global_styling/mixins/_header.scss
  src/themes/oui-next/global_styling/mixins/_header.scss
  yarn.lock
Labels: backport 1.x, distinguished-contributor

#973 Update ouiTextSubduedColor in `next` dark theme
  CHANGELOG.md
  src/themes/oui-next/oui_next_colors_dark.scss
Labels: valued-contributor

#982 Bump version to 1.3.0-beta.1
  package.json
Labels: skip-changelog, distinguished-contributor

#990 Remove `calc` usage from SchemaItem styles
  CHANGELOG.md
  src/components/schema/_schema_item.scss
Labels: backport 1.x, all-star-contributor

#986 (OUI Docs) Update Form validation page
  CHANGELOG.md
  src-docs/src/views/form_validation/form_validation_example.js
Labels: backport 1.x, first-time-contributor

#985 Add dismissible prop to OuiCallOut
  CHANGELOG.md
  src-docs/src/views/call_out/info.js
  src/components/call_out/__snapshots__/call_out.test.tsx.snap
  src/components/call_out/_call_out.scss
  src/components/call_out/call_out.test.tsx
  src/components/call_out/call_out.tsx
Labels: backport 1.x, 1.3, repeat-contributor

#1004 Adjust background color of `OuiToolTip`
  CHANGELOG.md
  src/themes/oui-next/global_styling/variables/_tool_tip.scss
Labels: backport 1.x, valued-contributor, 1.3

#1003 Rename onDismissible to onDismiss for OuiCallOut
  src-docs/src/views/call_out/info.js
  src/components/call_out/__snapshots__/call_out.test.tsx.snap
  src/components/call_out/call_out.test.tsx
  src/components/call_out/call_out.tsx
Labels: backport 1.x, skip-changelog, 1.3, repeat-contributor

#1005 Adjust `$ouiFormInputGroupLabelBackground color` in dark `next` theme
  CHANGELOG.md
  src/themes/oui-next/global_styling/variables/_form.scss
Labels: backport 1.x, valued-contributor, 1.3

#856 Add new "middle-out" order prop option to `OuiPaletteColorBlind'
  CHANGELOG.md
  src-docs/src/views/color_palette/color_palette.js
  src-docs/src/views/color_palette/props_info.js
  src/services/color/oui_palettes.ts
Labels: backport 1.x, 1.3, repeat-contributor
