Repository opensearch-project/oui, pull requests merged in 2023-01, with the labels that each got.

#180 Add WhiteSource config file
  .whitesource
  whitesource.config
Labels: enhancement, dependencies

#206 Update ramda from 0.25.0 to 0.27.1
  package.json
  yarn.lock
Labels: dependencies, backport 1.0

#225 Fix docs site default theme
  src-docs/src/components/with_theme/theme_context.tsx
Labels: backport 1.0

#247 Updated text in Section Positions
  src-docs/src/views/flex/flex_align_center.js
  src-docs/src/views/flex/flex_grow_zero.tsx
  src-docs/src/views/flex/flex_item.tsx
  src-docs/src/views/flex/flex_justify.js
  src-docs/src/views/flex/flex_justify_between.js
  src-docs/src/views/flex/flex_justify_evenly.js
Labels: backport 1.0
