Repository opensearch-project/oui, pull requests merged in 2024-10, with the labels that each got.

#1426 Compress searchbar
  CHANGELOG.md
  src-docs/src/views/search_bar/props_info.js
  src-docs/src/views/search_bar/search_bar.js
  src-docs/src/views/search_bar/search_bar_filters.js
  src/components/search_bar/query/__snapshots__/ast_to_es_query_string.test.ts.snap
  src/components/search_bar/query/__snapshots__/ast_to_opensearch_query_dsl.test.ts.snap
  src/components/search_bar/query/__snapshots__/ast_to_opensearch_query_string.test.ts.snap
  src/components/search_bar/query/ast_to_opensearch_query_dsl.test.ts
  src/components/search_bar/query/ast_to_opensearch_query_dsl.ts
  src/components/search_bar/query/ast_to_opensearch_query_string.test.ts
  src/components/search_bar/query/ast_to_opensearch_query_string.ts
  src/components/search_bar/query/query.ts
  src/components/search_bar/search_bar.tsx
Labels: backport 1.x, distinguished-contributor

#1430 Update v9 theme colors and revert button background colors
  CHANGELOG.md
  src/components/button/_button.scss
  src/components/button/button_group/_button_group.scss
  src/components/split_button/_split_button_control.scss
  src/global_styling/variables/_buttons.scss
  src/global_styling/variables/_side_nav.scss
  src/themes/oui-next/global_styling/variables/_buttons.scss
  src/themes/oui-next/global_styling/variables/_side_nav.scss
  src/themes/v9/global_styling/variables/_buttons.scss
  src/themes/v9/global_styling/variables/_colors.scss
  src/themes/v9/global_styling/variables/_header.scss
  src/themes/v9/global_styling/variables/_panel.scss
  src/themes/v9/global_styling/variables/_side_nav.scss
  src/themes/v9/global_styling/variables/_tool_tip.scss
  src/themes/v9/v9_colors_dark.scss
Labels: seasoned-contributor

#1432 Bump changelog and package.json for 1.15 release
  CHANGELOG.md
  package.json
Labels: seasoned-contributor

#1433 Update changelog for 1.15 release
  CHANGELOG.md
Labels: seasoned-contributor

#1435 Update filter icon
  CHANGELOG.md
  src/components/icon/__snapshots__/icon.test.tsx.snap
  src/components/icon/assets/filter.js
  src/components/icon/assets/filter.svg
Labels: all-star-contributor

#1437 Update sidenav and tooltip colors in v9 theme
  CHANGELOG.md
  src/themes/v9/global_styling/variables/_side_nav.scss
  src/themes/v9/global_styling/variables/_tool_tip.scss
Labels: all-star-contributor

#1440 Update changelog and package.json for 1.16 release
  CHANGELOG.md
  package.json
Labels: all-star-contributor

#1441 Update changelog for 1.16 release
  CHANGELOG.md
Labels: all-star-contributor

#1443 Add icons for getting started cards
  CHANGELOG.md
  src-docs/src/views/icon/icons.js
  src/components/icon/__snapshots__/icon.test.tsx.snap
  src/components/icon/assets/bookOpen.js
  src/components/icon/assets/bookOpen.svg
  src/components/icon/assets/compass.js
  src/components/icon/assets/compass.svg
  src/components/icon/assets/dashboard.js
  src/components/icon/assets/dashboard.svg
  src/components/icon/assets/functionAdd.js
  src/components/icon/assets/functionAdd.svg
  src/components/icon/assets/lineChart.js
  src/components/icon/assets/lineChart.svg
  src/components/icon/assets/pulse.js
  src/components/icon/assets/pulse.svg
  src/components/icon/assets/radar.js
  src/components/icon/assets/radar.svg
  src/components/icon/assets/rocket.js
  src/components/icon/assets/rocket.svg
  src/components/icon/icon.tsx
Labels: backport 1.x, all-star-contributor

#1446 Update v9 theme colors for light and dark mode
  CHANGELOG.md
  src/themes/v9/global_styling/variables/_buttons.scss
  src/themes/v9/global_styling/variables/_colors.scss
  src/themes/v9/global_styling/variables/_form.scss
  src/themes/v9/global_styling/variables/_shadows.scss
  src/themes/v9/global_styling/variables/_side_nav.scss
  src/themes/v9/global_styling/variables/_tool_tip.scss
  src/themes/v9/v9_colors_dark.scss
Labels: backport 1.x, all-star-contributor

#1448 Update version and changelog for 1.17 release
  CHANGELOG.md
  package.json
Labels: all-star-contributor

#1449 Update changelog for 1.17 release
  CHANGELOG.md
Labels: all-star-contributor

#1452 feat: add sparkle_filled icon
  CHANGELOG.md
  src-docs/src/views/icon/icons.js
  src/components/icon/__snapshots__/icon.test.tsx.snap
  src/components/icon/assets/sparkle_filled.js
  src/components/icon/assets/sparkle_filled.svg
  src/components/icon/icon.tsx
Labels: first-time-contributor
