Repository opensearch-project/oui, pull requests merged in 2024-01, with the labels that each got.

#1162 [OSCI][BUG] Fixing bug for making playground toggle button available in OUI v2.0
  CHANGELOG.md
  src-docs/src/components/guide_section/guide_section.tsx
Labels: first-time-contributor, OSCI

#1144 [OSCI] Clean/breadcrumb updates - Refactoring use of 'let' for 'const' keyword and CSS modifier '--last' for one class only
  CHANGELOG.md
  src/components/breadcrumbs/_breadcrumbs.scss
  src/components/breadcrumbs/breadcrumbs.tsx
Labels: first-time-contributor, OSCI

#1160 [OSCI][BUG] Fixing bug in icon-only buttons for showing info tooltip when hovered
  CHANGELOG.md
  src/components/button/button_content.tsx
Labels: backport 1.x, first-time-contributor, OSCI

#1120 Add CSS `display-none` utility
  CHANGELOG.md
  src-docs/src/views/utility_classes/utility_classes.js
  src/global_styling/utility/_utility.scss
  src/themes/oui-next/global_styling/utility/_utility.scss
Labels: backport 1.x, first-time-contributor, OSCI

#1135 [OSCI][CLEAN] Audit unused dependencies in OUI
  CHANGELOG.md
  package.json
  yarn.lock
Labels: first-time-contributor, OSCI

#1198 Eliminate screenreader content when copying and pasting data grid table
  CHANGELOG.md
  src/global_styling/mixins/_helpers.scss
  src/themes/oui-next/global_styling/mixins/_helpers.scss
Labels: backport 1.x, repeat-contributor
