Repository opensearch-project/oui, pull requests merged in 2024-11, with the labels that each got.

#1456 update figma link to latest v2
  CHANGELOG.md
  src-docs/src/components/guide_page/guide_page_header.tsx
Labels: first-time-contributor

#755 feat: vertical oriented button group
  CHANGELOG.md
  src-docs/src/views/button/button_example.js
  src-docs/src/views/button/button_group_vertical.js
  src/components/button/button_group/__snapshots__/button_group.test.tsx.snap
  src/components/button/button_group/_button_group.scss
  src/components/button/button_group/_button_group_button.scss
  src/components/button/button_group/button_group.test.tsx
  src/components/button/button_group/button_group.tsx
Labels: backport 1.x, first-time-contributor

#1460 Update colors for v9 theme light
  CHANGELOG.md
  src/themes/v9/global_styling/variables/_buttons.scss
  src/themes/v9/global_styling/variables/_colors.scss
  src/themes/v9/global_styling/variables/_form.scss
  src/themes/v9/global_styling/variables/_panel.scss
  src/themes/v9/global_styling/variables/_shadows.scss
  src/themes/v9/global_styling/variables/_tool_tip.scss
Labels: backport 1.x, all-star-contributor

#1466 Update changelog and package.json for 1.18 release
  CHANGELOG.md
  package.json
Labels: all-star-contributor
