Repository opensearch-project/oui, pull requests merged in 2024-09, with the labels that each got.

#1380 Add compressed styling to OuiDatePicker and OuiDatePickerRange
  CHANGELOG.md
  src-docs/src/views/date_picker/date_picker.js
  src-docs/src/views/date_picker/date_picker_example.js
  src-docs/src/views/date_picker/playground.js
  src-docs/src/views/date_picker/range.js
  src-docs/src/views/date_picker/states.js
  src/components/date_picker/__snapshots__/date_picker.test.tsx.snap
  src/components/date_picker/_date_picker_range.scss
  src/components/date_picker/date_picker.tsx
  src/components/date_picker/date_picker_range.tsx
Labels: backport 1.x, distinguished-contributor

#1381 Consume the `className` prop in OuiSearchBar
  CHANGELOG.md
  src/components/search_bar/__snapshots__/search_bar.test.tsx.snap
  src/components/search_bar/search_bar.tsx
Labels: backport 1.x, distinguished-contributor

#1387 Expand definition of `$ouiBreakpoints` to include `xxl` and `xxxl`
  CHANGELOG.md
  src/global_styling/variables/_responsive.scss
  src/themes/oui-next/global_styling/variables/_responsive.scss
  src/themes/v9/global_styling/variables/_responsive.scss
Labels: backport 1.x, distinguished-contributor

#1389 Remove scaling of heading elements
  CHANGELOG.md
  src-docs/src/views/text/text.js
  src-docs/src/views/text/text_small.js
  src/components/text/_text.scss
  src/themes/v9/global_styling/variables/_typography.scss
Labels: distinguished-contributor

#1391 Make the space between search bar and table rows match the compressed state of the search box
  CHANGELOG.md
  src-docs/src/views/tables/in_memory/in_memory_search.js
  src/components/basic_table/in_memory_table.tsx
Labels: backport 1.x, distinguished-contributor

#1394 Move Iskander, Andrey, and Sergey to the Emeritus list
  .github/CODEOWNERS
  CHANGELOG.md
  MAINTAINERS.md
Labels: backport 1.x, distinguished-contributor

#1398 fix: update v9 light primary color
  src/themes/v9/global_styling/variables/_colors.scss
  src/themes/v9/v9_colors_dark.scss
Labels: backport 1.x, skip-changelog, seasoned-contributor

#1402 fix: updates to v9 theme colors
  src/themes/v9/global_styling/variables/_buttons.scss
  src/themes/v9/global_styling/variables/_colors.scss
  src/themes/v9/v9_colors_dark.scss
Labels: backport 1.x, skip-changelog, seasoned-contributor

#1401 Adjust OuiSimplifiedBreadcrumbs alignment, colors, and tailing slash
  CHANGELOG.md
  src-docs/src/views/breadcrumbs/breadcrumbs_example.js
  src-docs/src/views/breadcrumbs/display_breadcrumbs_toggles.js
  src-docs/src/views/breadcrumbs/simplified_breadcrumbs.js
  src/components/breadcrumbs/__snapshots__/breadcrumbs.test.tsx.snap
  src/components/breadcrumbs/__snapshots__/breadcrumbs_simplified.test.tsx.snap
  src/components/breadcrumbs/_breadcrumbs.scss
  src/components/breadcrumbs/_breadcrumbs_simplified.scss
  src/components/breadcrumbs/_index.scss
  src/components/breadcrumbs/_variables.scss
  src/components/breadcrumbs/breadcrumbs.tsx
  src/components/breadcrumbs/index.ts
  src/components/breadcrumbs/simplified_breadcrumbs/__snapshots__/simplified_breadcrumbs.test.tsx.snap
  src/components/breadcrumbs/simplified_breadcrumbs/_index.scss
  src/components/breadcrumbs/simplified_breadcrumbs/_simplified_breadcrumbs.scss
  src/components/breadcrumbs/simplified_breadcrumbs/index.ts
  src/components/breadcrumbs/simplified_breadcrumbs/simplified_breadcrumbs.test.tsx
  src/components/breadcrumbs/simplified_breadcrumbs/simplified_breadcrumbs.tsx
  src/components/header/header_breadcrumbs/__snapshots__/header_breadcrumbs.test.tsx.snap
  src/services/breakpoint.test.ts
  src/services/breakpoint.ts
Labels: backport 1.x, distinguished-contributor

#1400 Upgrade build-lib version in release pipeline to accomodate new changes
  jenkins/release.JenkinsFile
Labels: skip-changelog, repeat-contributor

#1397 Bump changelog and version for 1.13 release
  CHANGELOG.md
  package.json
  yarn.lock
Labels: distinguished-contributor

#1412 1.13 update changelog
  CHANGELOG.md
Labels: skip-changelog, seasoned-contributor

#1416 fix: Update components to respect new breakpoints
  CHANGELOG.md
  src-docs/src/views/guidelines/colors/_color_section.scss
  src/components/header/header_links/header_links.test.tsx
  src/components/page/page_header/_page_header_content.scss
  src/components/page/page_side_bar/_page_side_bar.scss
  src/components/page/page_template.tsx
  src/components/search_bar/_search_bar.scss
  src/components/table/_responsive.scss
  src/components/table/_table.scss
  src/global_styling/mixins/_header.scss
  src/themes/oui-next/global_styling/mixins/_header.scss
  src/themes/v9/global_styling/mixins/_header.scss
Labels: seasoned-contributor

#1417 Additional updates to v9 theme
  CHANGELOG.md
  i18ntokens.json
  src-docs/src/views/card/card_example.js
  src-docs/src/views/panel/panel_color.js
  src-docs/src/views/panel/panel_example.js
  src/components/button/_button.scss
  src/components/button/button_group/_button_group.scss
  src/components/card/card.tsx
  src/components/form/form_control_layout/_form_control_layout.scss
  src/components/link/_mixins.scss
  src/components/panel/__snapshots__/panel.test.tsx.snap
  src/components/panel/panel.tsx
  src/components/side_nav/_index.scss
  src/components/split_button/_split_button_control.scss
  src/global_styling/variables/_buttons.scss
  src/global_styling/variables/_index.scss
  src/global_styling/variables/_panel.scss
  src/global_styling/variables/_side_nav.scss
  src/themes/oui-next/global_styling/variables/_buttons.scss
  src/themes/oui-next/global_styling/variables/_index.scss
  src/themes/oui-next/global_styling/variables/_panel.scss
  src/themes/oui-next/global_styling/variables/_side_nav.scss
  src/themes/v9/global_styling/variables/_buttons.scss
  src/themes/v9/global_styling/variables/_colors.scss
  src/themes/v9/global_styling/variables/_form.scss
  src/themes/v9/global_styling/variables/_index.scss
  src/themes/v9/global_styling/variables/_panel.scss
  src/themes/v9/global_styling/variables/_side_nav.scss
  src/themes/v9/global_styling/variables/_typography.scss
Labels: seasoned-contributor

#1419 [Manual Backport 1.x] fix: Update components to respect new breakpoints (#1416)
  CHANGELOG.md
  src-docs/src/views/guidelines/colors/_color_section.scss
  src/components/header/header_links/header_links.test.tsx
  src/components/page/page_header/_page_header_content.scss
  src/components/page/page_side_bar/_page_side_bar.scss
  src/components/page/page_template.tsx
  src/components/search_bar/_search_bar.scss
  src/components/table/_responsive.scss
  src/components/table/_table.scss
  src/global_styling/mixins/_header.scss
  src/themes/oui-next/global_styling/mixins/_header.scss
  src/themes/v9/global_styling/mixins/_header.scss
Labels: skip-changelog, seasoned-contributor

#1414 Temporary fix for Chrome's problem with rendering mask images
  CHANGELOG.md
  src/global_styling/mixins/_shadow.scss
  src/themes/oui-next/global_styling/mixins/_shadow.scss
  src/themes/v9/global_styling/mixins/_shadow.scss
Labels: backport 1.x, distinguished-contributor

#1421 Bump changelog and package.json for 1.14 release
  CHANGELOG.md
  package.json
Labels: seasoned-contributor

#1422 Update v9 colors and typography
  src-docs/src/theme_v9_dark.scss
  src-docs/src/theme_v9_light.scss
  src/themes/v9/global_styling/variables/_buttons.scss
  src/themes/v9/global_styling/variables/_colors.scss
  src/themes/v9/global_styling/variables/_side_nav.scss
  src/themes/v9/global_styling/variables/_typography.scss
  src/themes/v9/v9_colors_dark.scss
  wiki/consuming.md
Labels: backport 1.x, skip-changelog, seasoned-contributor

#1424 1.14 udpate changelog
  CHANGELOG.md
Labels: seasoned-contributor
