Repository opensearch-project/oui, pull requests merged in 2024-07, with the labels that each got.

#1283 feat: adjust popover and context menu title styles and tooltip padding
  CHANGELOG.md
  src/components/context_menu/_context_menu_panel.scss
  src/components/tool_tip/_tool_tip.scss
  src/global_styling/mixins/_popover.scss
  src/themes/oui-next/global_styling/mixins/_popover.scss
Labels: first-time-contributor

#1286 feat: make SuperUpdateButton's button secondary
  CHANGELOG.md
  src/components/date_picker/super_date_picker/__snapshots__/super_update_button.test.tsx.snap
  src/components/date_picker/super_date_picker/super_update_button.tsx
Labels: backport 1.x, first-time-contributor

#1282 feat: use faster animations for modals, popovers, and tooltips
  CHANGELOG.md
  src/components/modal/_modal.scss
  src/components/popover/_popover.scss
  src/components/tool_tip/_tool_tip.scss
  src/global_styling/mixins/_tool_tip.scss
  src/themes/oui-next/global_styling/mixins/_tool_tip.scss
Labels: backport 1.x, first-time-contributor, 1.7

#1281 feat: use consistent font sizes in buttons
  CHANGELOG.md
  src/components/button/button_group/_button_group_button.scss
  src/global_styling/mixins/_button.scss
  src/themes/oui-next/global_styling/mixins/_button.scss
Labels: backport 1.x, first-time-contributor, 1.7

#1285 feat: remove Button translations and add inset shadow on active
  CHANGELOG.md
  src/components/button/_button.scss
  src/components/button/button_icon/_button_icon.scss
  src/components/split_button/_split_button_control.scss
  src/global_styling/mixins/_button.scss
  src/global_styling/mixins/_shadow.scss
  src/themes/oui-next/global_styling/mixins/_button.scss
  src/themes/oui-next/global_styling/mixins/_shadow.scss
Labels: backport 1.x, first-time-contributor, 1.7

#1209 Bufix/split-button-single
  CHANGELOG.md
  src-docs/src/views/split_button/split_button_example.js
  src-docs/src/views/split_button/split_button_simple.js
  src/components/split_button/__snapshots__/split_button.test.tsx.snap
  src/components/split_button/__snapshots__/split_button_control.test.tsx.snap
  src/components/split_button/split_button.test.tsx
  src/components/split_button/split_button.tsx
  src/components/split_button/split_button_control.test.tsx
  src/components/split_button/split_button_control.tsx
Labels: first-time-contributor

#1279 Add docs for validating OUI changes in OpenSearch-Dashboards
  CHANGELOG.md
  DEVELOPER_GUIDE.md
  wiki/validating-with-opensearch-dashboards.md
Labels: first-time-contributor

#1182 [Enhance] Add Explanation for external Prop in OuiLink
  src-docs/src/views/link/link.js
Labels: backport 1.x, valued-contributor, 1.7

#1301 Add Compressed form components, color-picker, and combobox, and small button components and filter-button
  CHANGELOG.md
  packages/eslint-plugin/rules/href_or_on_click.js
  packages/eslint-plugin/rules/href_or_on_click.test.js
  src/components/button/button.tsx
  src/components/button/button_empty/button_empty.tsx
  src/components/button/button_empty/index.ts
  src/components/button/button_group/button_group.tsx
  src/components/button/button_group/index.ts
  src/components/button/button_icon/button_icon.tsx
  src/components/button/button_icon/index.ts
  src/components/button/index.ts
  src/components/color_picker/color_picker.tsx
  src/components/color_picker/index.ts
  src/components/combo_box/combo_box.tsx
  src/components/combo_box/index.ts
  src/components/filter_group/filter_button.tsx
  src/components/filter_group/index.ts
  src/components/form/checkbox/checkbox.tsx
  src/components/form/checkbox/checkbox_group.tsx
  src/components/form/checkbox/index.ts
  src/components/form/field_number/field_number.tsx
  src/components/form/field_number/index.ts
  src/components/form/field_password/field_password.tsx
  src/components/form/field_password/index.ts
  src/components/form/field_search/field_search.tsx
  src/components/form/field_search/index.ts
  src/components/form/field_text/field_text.tsx
  src/components/form/field_text/index.ts
  src/components/form/file_picker/file_picker.tsx
  src/components/form/file_picker/index.ts
  src/components/form/form_fieldset/form_legend.tsx
  src/components/form/form_fieldset/index.ts
  src/components/form/form_row/form_row.tsx
  src/components/form/form_row/index.ts
  src/components/form/radio/index.ts
  src/components/form/radio/radio.tsx
  src/components/form/radio/radio_group.tsx
  src/components/form/range/dual_range.tsx
  src/components/form/range/index.ts
  src/components/form/range/range.tsx
  src/components/form/select/index.ts
  src/components/form/select/select.tsx
  src/components/form/super_select/index.ts
  src/components/form/super_select/super_select.tsx
  src/components/form/switch/index.ts
  src/components/form/switch/switch.tsx
  src/components/form/text_area/index.ts
  src/components/form/text_area/text_area.tsx
  src/components/index.js
Labels: distinguished-contributor

#1303 Updating changelog and version
  CHANGELOG.md
  i18ntokens.json
  package.json
Labels: distinguished-contributor

#1304 Update 1.7 changelog
  CHANGELOG.md
Labels: distinguished-contributor, 1.7

#1306 fix: Fix next reset for code blocks and super update button icon
  CHANGELOG.md
  src/components/date_picker/super_date_picker/__snapshots__/super_update_button.test.tsx.snap
  src/components/date_picker/super_date_picker/super_update_button.tsx
  src/themes/oui-next/global_styling/reset/_reset.scss
Labels: backport 1.x, valued-contributor, 1.8

#1309 Add Viraj as a maintainer
  .github/CODEOWNERS
  CHANGELOG.md
  MAINTAINERS.md
Labels: backport 1.x, distinguished-contributor

#1312 Bump version post 1.7 release
  CHANGELOG.md
  package.json
Labels: distinguished-contributor

#1311 Fix the appearance of form controls in grouped layouts
  CHANGELOG.md
  src-docs/src/views/form_controls/prepend_append.js
  src/components/form/form_control_layout/_form_control_layout.scss
Labels: backport 1.x, distinguished-contributor, 1.8

#1314 Sync 1.x changelog
  CHANGELOG.md
Labels: distinguished-contributor

#1315 fix: Make QuickSelectPopover padding small in SuperDatePicker
  CHANGELOG.md
  src/components/date_picker/super_date_picker/quick_select_popover/__snapshots__/quick_select_popover.test.tsx.snap
  src/components/date_picker/super_date_picker/quick_select_popover/quick_select_popover.tsx
Labels: backport 1.x, valued-contributor, 1.8

#1318 Update changelog for 1.8 release
  CHANGELOG.md
Labels: distinguished-contributor

#1322 [Manual backport 1.8] Introduce compressed appearance for OuiSuperDatePicker (#1307)
  CHANGELOG.md
  src-docs/src/views/super_date_picker/super_date_picker_config.js
  src/components/date_picker/date_picker_range.tsx
  src/components/date_picker/super_date_picker/__snapshots__/super_date_picker.test.tsx.snap
  src/components/date_picker/super_date_picker/__snapshots__/super_update_button.test.tsx.snap
  src/components/date_picker/super_date_picker/_super_date_picker.scss
  src/components/date_picker/super_date_picker/date_popover/_date_popover_button.scss
  src/components/date_picker/super_date_picker/date_popover/date_popover_button.tsx
  src/components/date_picker/super_date_picker/super_date_picker.tsx
  src/components/date_picker/super_date_picker/super_update_button.tsx
Labels: distinguished-contributor

#1323 Bump 1.8.1
  package.json
Labels: skip-changelog, distinguished-contributor
