Repository opensearch-project/oui, pull requests merged in 2024-08, with the labels that each got.

#1321 [Manual backport 1.x] Introduce compressed appearance for OuiSuperDatePicker (#1307)
  CHANGELOG.md
  src-docs/src/views/super_date_picker/super_date_picker_config.js
  src/components/date_picker/date_picker_range.tsx
  src/components/date_picker/super_date_picker/__snapshots__/super_date_picker.test.tsx.snap
  src/components/date_picker/super_date_picker/__snapshots__/super_update_button.test.tsx.snap
  src/components/date_picker/super_date_picker/_super_date_picker.scss
  src/components/date_picker/super_date_picker/date_popover/_date_popover_button.scss
  src/components/date_picker/super_date_picker/date_popover/date_popover_button.tsx
  src/components/date_picker/super_date_picker/super_date_picker.tsx
  src/components/date_picker/super_date_picker/super_update_button.tsx
Labels: distinguished-contributor, 1.8

#1325 Fix export of OuiCompressedSuperDatePicker
  CHANGELOG.md
  src/components/date_picker/super_date_picker/index.ts
  src/components/index.js
Labels: backport 1.x, distinguished-contributor, 1.8, backport 1.8

#1320 fix: Fix now button to be secondary in SuperDatePicker
  CHANGELOG.md
  src/components/date_picker/super_date_picker/date_popover/date_popover_content.tsx
Labels: backport 1.x, valued-contributor

#1329 Prepare for patch release 1.8.2
  i18ntokens.json
  package.json
  yarn.lock
Labels: skip-changelog, distinguished-contributor

#1332 Add display type and color to OuiSwitch
  CHANGELOG.md
  src/components/form/switch/__snapshots__/switch.test.tsx.snap
  src/components/form/switch/_switch.scss
  src/components/form/switch/index.ts
  src/components/form/switch/switch.tsx
  src/global_styling/variables/_form.scss
  src/themes/oui-next/global_styling/variables/_form.scss
Labels: backport 1.x, distinguished-contributor

#1334 Sync changelog for 1.9.0 release
  CHANGELOG.md
Labels: distinguished-contributor

#1335 Prepare for 1.9.0 release
  CHANGELOG.md
  i18ntokens.json
  package.json
  yarn.lock
Labels: distinguished-contributor

#1338 Fixes combobox height with appendees
  CHANGELOG.md
  src/components/combo_box/_combo_box.scss
Labels: first-time-contributor

#1342 Update styling for empty button and date picker icon
  CHANGELOG.md
  src/components/button/button_empty/_button_empty.scss
  src/components/date_picker/super_date_picker/quick_select_popover/_quick_select_popover.scss
Labels: backport 1.x, first-time-contributor

#1346 Add history icon and alias it as recent
  CHANGELOG.md
  src-docs/src/views/icon/icons.js
  src/components/icon/__snapshots__/icon.test.tsx.snap
  src/components/icon/assets/history.js
  src/components/icon/assets/history.svg
  src/components/icon/icon.tsx
Labels: backport 1.x, distinguished-contributor

#1354 Introduce compressed OuiSearchBar
  CHANGELOG.md
  src-docs/src/views/search_bar/props_info.js
  src/components/search_bar/__snapshots__/search_filters.test.tsx.snap
  src/components/search_bar/filters/field_value_selection_filter.tsx
  src/components/search_bar/filters/field_value_toggle_filter.tsx
  src/components/search_bar/filters/field_value_toggle_group_filter.tsx
  src/components/search_bar/filters/is_filter.tsx
  src/components/search_bar/search_bar.tsx
  src/components/search_bar/search_filters.tsx
Labels: backport 1.x, distinguished-contributor

#1355 Fix docs error when accessing some props
  CHANGELOG.md
  package.json
  yarn.lock
Labels: distinguished-contributor

#1359 Introduce `$ouiLegibilityMaxWidth` variable and `ouiLegibilityMaxWidth` mixin
  CHANGELOG.md
  src/global_styling/mixins/_typography.scss
  src/global_styling/variables/_typography.scss
  src/themes/oui-next/global_styling/mixins/_typography.scss
  src/themes/oui-next/global_styling/variables/_typography.scss
  src/themes/v9/global_styling/mixins/_typography.scss
  src/themes/v9/global_styling/variables/_typography.scss
Labels: backport 1.x, distinguished-contributor

#1362 Prepare for 1.10.0 release
  CHANGELOG.md
  i18ntokens.json
  package.json
  yarn.lock
Labels: distinguished-contributor

#1363 Update changelog for 1.10
  CHANGELOG.md
Labels: distinguished-contributor

#1365 Add workspace icons
  CHANGELOG.md
  src-docs/src/views/icon/icon_example.js
  src-docs/src/views/icon/workspace.js
  src/components/icon/__snapshots__/icon.test.tsx.snap
  src/components/icon/assets/workspace/wsAnalytics.js
  src/components/icon/assets/workspace/wsAnalytics.svg
  src/components/icon/assets/workspace/wsEssentials.js
  src/components/icon/assets/workspace/wsEssentials.svg
  src/components/icon/assets/workspace/wsObservability.js
  src/components/icon/assets/workspace/wsObservability.svg
  src/components/icon/assets/workspace/wsSearch.js
  src/components/icon/assets/workspace/wsSearch.svg
  src/components/icon/assets/workspace/wsSecurityAnalytics.js
  src/components/icon/assets/workspace/wsSecurityAnalytics.svg
  src/components/icon/assets/workspace/wsSelector.js
  src/components/icon/assets/workspace/wsSelector.svg
  src/components/icon/icon.tsx
Labels: backport 1.x, distinguished-contributor

#1367 Add button icon gap prop
  CHANGELOG.md
  src/components/basic_table/__snapshots__/in_memory_table.test.tsx.snap
  src/components/button/__snapshots__/button.test.tsx.snap
  src/components/button/button.test.tsx
  src/components/button/button.tsx
  src/components/button/button_content.tsx
  src/components/button/button_empty/__snapshots__/button_empty.test.tsx.snap
  src/components/button/button_empty/button_empty.test.tsx
  src/components/button/button_empty/button_empty.tsx
  src/components/control_bar/__snapshots__/control_bar.test.tsx.snap
  src/components/split_button/__snapshots__/split_button.test.tsx.snap
  src/global_styling/mixins/_button.scss
  src/global_styling/variables/_size.scss
  src/themes/oui-next/global_styling/mixins/_button.scss
  src/themes/oui-next/global_styling/variables/_size.scss
  src/themes/v9/global_styling/mixins/_button.scss
  src/themes/v9/global_styling/variables/_size.scss
Labels: backport 1.x, distinguished-contributor

#1368 Allow controlling the gap between the icon and the content of OuiButton and OuiButtonEmpty (#1367)
  CHANGELOG.md
  package.json
  src/components/basic_table/__snapshots__/in_memory_table.test.tsx.snap
  src/components/button/__snapshots__/button.test.tsx.snap
  src/components/button/button.test.tsx
  src/components/button/button.tsx
  src/components/button/button_content.tsx
  src/components/button/button_empty/__snapshots__/button_empty.test.tsx.snap
  src/components/button/button_empty/button_empty.test.tsx
  src/components/button/button_empty/button_empty.tsx
  src/components/control_bar/__snapshots__/control_bar.test.tsx.snap
  src/components/split_button/__snapshots__/split_button.test.tsx.snap
  src/global_styling/mixins/_button.scss
  src/global_styling/variables/_size.scss
  src/themes/oui-next/global_styling/mixins/_button.scss
  src/themes/oui-next/global_styling/variables/_size.scss
  src/themes/v9/global_styling/mixins/_button.scss
  src/themes/v9/global_styling/variables/_size.scss
Labels: distinguished-contributor

#1369 Update changelog for 1.11 release
  CHANGELOG.md
Labels: distinguished-contributor

#1371 Fix combobox appearance when compressed and in-group
  CHANGELOG.md
  src/components/combo_box/_combo_box.scss
  src/components/combo_box/combo_box_input/_combo_box_pill.scss
  src/components/form/form_control_layout/_form_control_layout.scss
Labels: backport 1.x, distinguished-contributor

#1374 Create OuiSimplifiedBreadcrumbs and update OuiHeaderBreadcrumbs
  CHANGELOG.md
  i18ntokens.json
  src/components/breadcrumbs/__snapshots__/breadcrumbs_simplified.test.tsx.snap
  src/components/breadcrumbs/_breadcrumbs_simplified.scss
  src/components/breadcrumbs/_index.scss
  src/components/breadcrumbs/breadcrumbs.tsx
  src/components/breadcrumbs/breadcrumbs_simplified.test.tsx
  src/components/breadcrumbs/breadcrumbs_simplified.tsx
  src/components/breadcrumbs/index.ts
  src/components/header/header_breadcrumbs/__snapshots__/header_breadcrumbs.test.tsx.snap
  src/components/header/header_breadcrumbs/_header_breadcrumbs.scss
  src/components/header/header_breadcrumbs/header_breadcrumbs.test.tsx
  src/components/header/header_breadcrumbs/header_breadcrumbs.tsx
  src/components/index.js
Labels: first-time-contributor

#1373 fix: Updates to v9 colors, button/input styles, and typography
  CHANGELOG.md
  src/components/button/_button.scss
  src/components/button/button_group/_button_group.scss
  src/components/button/button_icon/_button_icon.scss
  src/components/date_picker/super_date_picker/_super_date_picker.scss
  src/components/form/switch/_switch.scss
  src/components/split_button/_split_button_control.scss
  src/global_styling/mixins/_button.scss
  src/themes/oui-next/global_styling/mixins/_button.scss
  src/themes/v9/global_styling/mixins/_button.scss
  src/themes/v9/global_styling/mixins/_form.scss
  src/themes/v9/global_styling/reset/_reset.scss
  src/themes/v9/global_styling/variables/_buttons.scss
  src/themes/v9/global_styling/variables/_colors.scss
  src/themes/v9/v9_colors_dark.scss
Labels: valued-contributor

#1377 [Backport-1.x] fix: Updates to v9 colors, button/input styles, and typography (#1373)
  CHANGELOG.md
  package.json
  src/components/button/_button.scss
  src/components/button/button_group/_button_group.scss
  src/components/button/button_icon/_button_icon.scss
  src/components/date_picker/super_date_picker/_super_date_picker.scss
  src/components/form/switch/_switch.scss
  src/components/split_button/_split_button_control.scss
  src/global_styling/mixins/_button.scss
  src/themes/oui-next/global_styling/mixins/_button.scss
  src/themes/v9/global_styling/mixins/_button.scss
  src/themes/v9/global_styling/mixins/_form.scss
  src/themes/v9/global_styling/reset/_reset.scss
  src/themes/v9/global_styling/variables/_buttons.scss
  src/themes/v9/global_styling/variables/_colors.scss
  src/themes/v9/v9_colors_dark.scss
Labels: valued-contributor

#1378 Fix changelog for 1.12 release
  CHANGELOG.md
Labels: valued-contributor
