Repository opensearch-project/oui, pull requests merged in 2024-02, with the labels that each got.

#1221 [Next Theme] Set base font size to 18px
  CHANGELOG.md
  src/components/suggest/_suggest_item.scss
  src/themes/oui-next/global_styling/mixins/_typography.scss
  src/themes/oui-next/global_styling/reset/_reset.scss
  src/themes/oui-next/global_styling/variables/_typography.scss
Labels: all-star-contributor

#1222 [Next Theme] Revert `font-weight` of OuiButton to normal from semi-bold
  CHANGELOG.md
  src/themes/oui-next/global_styling/mixins/_button.scss
Labels: all-star-contributor

#1223 Prevent collapsable button of a resizable from adding to the height when hidden
  CHANGELOG.md
  src/components/resizable_container/_resizable_collapse_button.scss
Labels: all-star-contributor

#1224 Prevent action buttons of OuiDataGridCell from moving the content
  CHANGELOG.md
  src/components/datagrid/_data_grid_data_row.scss
Labels: backport 1.x, all-star-contributor, 1.5

#1152 [Security] Remediate `axios` vulnerabilities and remove code sandbox links
  CHANGELOG.md
  package.json
  src-docs/src/components/codesandbox/index.js
  src-docs/src/components/codesandbox/link.js
  src-docs/src/components/guide_section/guide_section_parts/guide_section_code.tsx
  src-docs/src/views/form_controls/display_toggles.js
  src-docs/src/views/header/header_elastic_pattern.js
  yarn.lock
Labels: backport 1.x, seasoned-contributor, 1.5

#1234 Bump version on 1.5
  package.json
Labels: skip-changelog, valued-contributor

#1238 Update `i18ntokens` and bump version for 1.5.0-rc.2
  i18ntokens.json
  package.json
Labels: skip-changelog, all-star-contributor

#1241 Prevent collapsable button of a resizable from adding to the height when hidden
  CHANGELOG.md
  src/components/resizable_container/_resizable_collapse_button.scss
Labels: backport 1.x, 1.5, backport 1.5

#1245 [CVE-2023-26159] Bump `follow-redirects` to 1.15.5
  yarn.lock
Labels: skip-changelog, all-star-contributor, 1.5

#1242 Bump version to 1.5
  CHANGELOG.md
  package.json
Labels: all-star-contributor, 1.5

#1250 Fix datagrid lines
  CHANGELOG.md
  src/components/datagrid/_data_grid_data_row.scss
Labels: backport 1.x, all-star-contributor, backport 1.5

#1251 Bump version to 1.5.1
  CHANGELOG.md
  package.json
Labels: all-star-contributor
