Repository opensearch-project/oui, pull requests merged in 2025-02, with the labels that each got.

#1491 update upload-artifact and download-artifact to v4
  .github/workflows/build_and_test.yml
  CHANGELOG.md
Labels: repeat-contributor

#1492 Update maintainer alias from @d-rowe to @d-buckner
  .github/CODEOWNERS
  CHANGELOG.md
  MAINTAINERS.md
Labels: all-star-contributor

#1493 Clear ADMINS.md.
  ADMINS.md
Labels: first-time-contributor

#1490 fix EmptyButton text line-height
  CHANGELOG.md
  src/components/button/button_empty/_button_empty.scss
Labels: repeat-contributor
