Repository opensearch-project/oui, pull requests merged in 2025-06, with the labels that each got.

#1531 @babel/runtime upgrade
  CHANGELOG.md
  package.json
  yarn.lock
Labels: first-time-contributor

#1535 Add OpenSearch logo to page title
  CHANGELOG.md
  src-docs/src/views/page_header/page_header.js
Labels: first-time-contributor

#1549 Fix elliptic and axios CVE
  CHANGELOG.md
  yarn.lock
Labels: backport 1.x, first-time-contributor

#1557 Fix changelog formatting + add automated PRs
  CHANGELOG.md
Labels: backport 1.x, all-star-contributor

#1556 chore: Update jest to v26
  CHANGELOG.md
  package.json
  scripts/jest/setup/unmount_enzyme.js
  src/components/accordion/accordion.test.tsx
  src/components/code_editor/code_editor.test.tsx
  src/components/color_picker/color_picker.test.tsx
  src/components/color_picker/color_stops/color_stops.test.tsx
  src/components/combo_box/combo_box.test.tsx
  src/components/context_menu/context_menu_panel.test.tsx
  src/components/datagrid/data_grid.test.tsx
  src/components/focus_trap/focus_trap.test.tsx
  src/components/icon/__snapshots__/icon.test.tsx.snap
  src/components/markdown_editor/markdown_editor.test.tsx
  src/components/search_bar/query/ast.ts
  src/components/search_bar/query/index.ts
  src/components/search_bar/search_bar.tsx
  src/components/split_button/split_button.test.tsx
  yarn.lock
Labels: backport 1.x, all-star-contributor

#1567 Fix dev server configuration after webpack-dev-server upgrade in 1.19
  CHANGELOG.md
  package.json
  src-docs/dev.webpack.config.js
  src-docs/webpack.config.js
  src/components/search_bar/search_bar.tsx
  yarn.lock
Labels: backport 1.x, all-star-contributor

#1578 Update changelog for automated security fixes
  CHANGELOG.md
Labels: all-star-contributor

#1576 Upgrade jest to v27
  CHANGELOG.md
  package.json
  scripts/jest/config.json
  src/components/date_picker/super_date_picker/async_interval.test.ts
  src/components/error_boundary/error_boundary.test.tsx
  src/components/tool_tip/tool_tip.test.tsx
  yarn.lock
Labels: security fix, backport 1.x, all-star-contributor

#1575 Update eslint plugin jsx a11y 6.x
  CHANGELOG.md
  src/components/code/_code_block.tsx
  src/components/tool_tip/tool_tip.tsx
  yarn.lock
Labels: security fix, backport 1.x, all-star-contributor

#1586 Update TypeScript to 4.7.4
  CHANGELOG.md
  package.json
  src/components/basic_table/basic_table.tsx
  src/components/page/page_template.tsx
  src/components/search_bar/query/date_format.ts
  src/utils/prop_types/is.ts
  yarn.lock
Labels: backport 1.x, distinguished-contributor
