Repository opensearch-project/oui, pull requests merged in 2025-07, with the labels that each got.

#1593 Update babel-plugin-add-module-exports to 1.0.4
  CHANGELOG.md
  package.json
  yarn.lock
Labels: backport 1.x, distinguished-contributor

#1603 Update changelog and package.json for 1.20 release
  CHANGELOG.md
  package.json
Labels: distinguished-contributor

#1605 Fix changelog for 1.20 release
  CHANGELOG.md
Labels: distinguished-contributor

#1611 Add changelog entry for #1604
  CHANGELOG.md
Labels: distinguished-contributor

#1612 Add changelog entry for #1604
  CHANGELOG.md
Labels: distinguished-contributor

#1620 Fix changelog for 1.21 release
  CHANGELOG.md
Labels: repeat-contributor
